name: patient_tracker
description: "A health records management application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  get: ^4.7.2
  get_storage: ^2.1.1

  # UI / UX
  google_fonts: ^6.1.0
  salomon_bottom_bar: ^3.3.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  lottie: ^3.3.1
  flutter_animate: ^4.3.0
  url_launcher: ^6.2.2
  intl: ^0.17.0

  # Media
  image_picker: ^1.1.2
  path_provider: ^2.1.1
  path: ^1.8.3

  # Local storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

  # Notifications
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1

  # Charts
  charts_flutter_new: ^0.12.0

  # ✅ Firebase - Perbarui untuk kompatibilitas terbaru dengan Firebase 3.15.1
  http: ^1.2.0
  firebase_core: ^3.15.1  # Memperbarui firebase_core ke versi terbaru
  firebase_auth: ^5.5.1   # Memperbarui firebase_auth agar kompatibel dengan firebase_core ^3.15.1
  cloud_firestore: ^5.6.5  # Memperbarui cloud_firestore agar kompatibel dengan firebase_core ^3.15.1
  firebase_storage: ^12.4.9  # Menggunakan versi terbaru firebase_storage

  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/doctors/
    - assets/logos/
    - assets/onboarding/
    - assets/logo/app_logo.png
