// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthEDGUWnRuOr0RIVYJkOx-DBZmzOhGoE',
    appId: '1:1069015224617:web:2f139b791e1c3ef62e2738',
    messagingSenderId: '1069015224617',
    projectId: 'rumah-sakit-hermina-7f135',
    authDomain: 'rumah-sakit-hermina-7f135.firebaseapp.com',
    storageBucket: 'rumah-sakit-hermina-7f135.firebasestorage.app',
    measurementId: 'G-VZM27BHMGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXEPiu2fv_LDZZkH7UX5yQDmqzcgesuE',
    appId: '1:1069015224617:android:091810612ab1a93b2e2738',
    messagingSenderId: '1069015224617',
    projectId: 'rumah-sakit-hermina-7f135',
    storageBucket: 'rumah-sakit-hermina-7f135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz49lG1wstKaetJID9wfJyLWETVhb_6Do',
    appId: '1:1069015224617:ios:2ebf19ba59c8aa542e2738',
    messagingSenderId: '1069015224617',
    projectId: 'rumah-sakit-hermina-7f135',
    storageBucket: 'rumah-sakit-hermina-7f135.firebasestorage.app',
    iosBundleId: 'com.example.patientTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz49lG1wstKaetJID9wfJyLWETVhb_6Do',
    appId: '1:1069015224617:ios:2ebf19ba59c8aa542e2738',
    messagingSenderId: '1069015224617',
    projectId: 'rumah-sakit-hermina-7f135',
    storageBucket: 'rumah-sakit-hermina-7f135.firebasestorage.app',
    iosBundleId: 'com.example.patientTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthEDGUWnRuOr0RIVYJkOx-DBZmzOhGoE',
    appId: '1:1069015224617:web:7b1dc6384370e40a2e2738',
    messagingSenderId: '1069015224617',
    projectId: 'rumah-sakit-hermina-7f135',
    authDomain: 'rumah-sakit-hermina-7f135.firebaseapp.com',
    storageBucket: 'rumah-sakit-hermina-7f135.firebasestorage.app',
    measurementId: 'G-4DGGQN00ZN',
  );

}